# Generated by Django 4.0.5 on 2022-11-10 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duIntegral', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小肚的积分')),
                ('xuanIntegral', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小轩的积分')),
            ],
        ),
    ]
