# Generated by Django 4.0.5 on 2022-11-10 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xiaoduIntegral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duIntegral', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小肚的积分')),
            ],
        ),
        migrations.CreateModel(
            name='xiaoxuanIntegral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuanIntegral', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小轩的积分')),
            ],
        ),
        migrations.DeleteModel(
            name='Integral',
        ),
    ]
