# Generated by Django 4.0.5 on 2022-11-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_xiaoduintegral_xiaoxuanintegral_delete_integral'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaoduintegral',
            name='name',
            field=models.CharField(default=1, max_length=6, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xiaoxuanintegral',
            name='name',
            field=models.CharField(default=1, max_length=6, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
