# Generated by Django 4.0.5 on 2022-11-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_xiaoduintegral_name_xiaoxuanintegral_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xiaoduintegral',
            old_name='duIntegral',
            new_name='Integral',
        ),
        migrations.RenameField(
            model_name='xiaoxuanintegral',
            old_name='xuanIntegral',
            new_name='Integral',
        ),
    ]
