# Generated by Django 4.0.5 on 2022-11-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_duintegral_xiaoduintegral_integral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsakName', models.CharField(max_length=10, verbose_name='任务名称')),
                ('taskDetails', models.CharField(max_length=100, verbose_name='任务详情')),
                ('taskAward', models.CharField(max_length=2, verbose_name='任务奖励积分')),
            ],
        ),
    ]
