# Generated by Django 4.0.5 on 2022-11-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='setTime',
            field=models.CharField(default=1, max_length=20, verbose_name='添加时间'),
            preserve_default=False,
        ),
    ]
