# Generated by Django 4.0.5 on 2022-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_task_settime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isFinish',
            field=models.SmallIntegerField(choices=[(1, '完成'), (2, '待完成')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
