# Generated by Django 4.0.5 on 2022-11-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_task_isfinish_alter_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tsakName',
            new_name='taskName',
        ),
    ]
