# Generated by Django 4.0.5 on 2022-11-28 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_tsakname_task_taskname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='商品名称')),
                ('numCommodity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='商品卡数量')),
            ],
        ),
    ]
